# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Категории проектов',
                'verbose_name': 'Категория проектов',
            },
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Мнемокод для представления (уникальный)')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Содержание страницы')),
            ],
            options={
                'verbose_name_plural': 'Главная страница',
                'verbose_name': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название работы')),
                ('unit', models.CharField(max_length=100, verbose_name='единица измерения')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта (код)')),
                ('price', models.IntegerField(verbose_name='Цена за ед.')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Виды Работ',
                'verbose_name': 'Вид Работы',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Категории работ',
                'verbose_name': 'Категория работ',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Мнемокод для представления (уникальный)')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок страницы')),
                ('description', models.TextField(verbose_name='Содержание страницы')),
                ('categories', models.ManyToManyField(to='web.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Объекты для портфолио',
                'verbose_name': 'Объект для портфолио',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('alt_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Альт. текст')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='Объект')),
            ],
            options={
                'verbose_name_plural': 'Фото объекта',
                'verbose_name': 'Фото объекта',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Сегменты рынка',
                'verbose_name': 'Сегмент рынка',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Специальность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('jobcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.JobCategory', verbose_name='Услуги')),
            ],
            options={
                'verbose_name_plural': 'Мастера',
                'verbose_name': 'Мастер',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='jobcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.JobCategory', verbose_name='Категория работ'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('jobcategory', 'name')]),
        ),
    ]
