# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='jobcategories',
        ),
        migrations.AddField(
            model_name='worker',
            name='jobcategories',
            field=models.ManyToManyField(to='web.JobCategory', verbose_name='Услуги'),
        ),
    ]
