# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170604_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта для связи')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name_plural': 'Emails',
                'verbose_name': 'Email',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон:')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name_plural': 'Телефоны',
                'verbose_name': 'Телефон',
            },
        ),
    ]
