# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_projectphoto_is_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, max_length=140, null=True, verbose_name='Краткое описание для списков'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='is_thumb',
            field=models.BooleanField(default=False, verbose_name='Использовать как иконку объекта'),
        ),
    ]
