# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_auto_20170702_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО (Если не указан логин)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactemail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactphone',
            name='contact',
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, max_length=140, null=True, verbose_name='Краткое описание для списков (до 140 симв.)'),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ContactPerson', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ContactPerson', verbose_name='Контактное лицо'),
        ),
    ]
