# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170717_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactphone',
            name='place_on_header',
            field=models.BooleanField(default=False, verbose_name='Размещать в заголовке'),
        ),
    ]
