# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170730_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактные лица'},
        ),
        migrations.AddField(
            model_name='contactperson',
            name='order',
            field=models.IntegerField(default=-1, verbose_name='Вес для сортировки по убыванию'),
        ),
    ]
