# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170805_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2017, 8, 12, 10, 18, 39, 493887))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2017, 8, 12, 10, 18, 39, 493917))),
                ('deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCommentatorSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_name', models.CharField(max_length=255, verbose_name='Имя (по умолчанию)')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail для отправки ссылки')),
                ('secret', models.CharField(max_length=20, unique=True, verbose_name='Секретный код')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='Объект')),
            ],
            options={
                'verbose_name_plural': 'Коды для генерации ссылки для комментатора',
                'verbose_name': 'Код для генерации ссылки для комментатора',
            },
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['-order'], 'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактные лица'},
        ),
    ]
