# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170812_1018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobcategory',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='jobcategories',
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='indexpage',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 27, 13, 0, 40, 885500)),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 27, 13, 0, 40, 885534)),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
