# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170812_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='secret',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 10, 13, 58, 502484)),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 10, 13, 58, 502561)),
        ),
    ]
